src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Releasedate = null;

    #[ORM\Column(length: 255)]
    private ?string $Author = null;

    #[ORM\Column(length: 255)]
    private ?string $Statut = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(?string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getReleasedate(): ?\DateTimeInterface
    {
        return $this->Releasedate;
    }

    public function setReleasedate(?\DateTimeInterface $Releasedate): self
    {
        $this->Releasedate = $Releasedate;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        $this->Statut = $Statut;
        $Statut = "Brouillon";
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/index/index.html.twig
{% extends "base.html.twig" %}


{% block body%}
	<div class="row">
		{% for article in articles|sort((b, a) => a.Releasedate <=> b.Releasedate)|slice (1, 3)  %}
			{% if article.Statut == "Publié" %}
				<div class="col-sm-6">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">{{ article.Title }}</h5>
							<p class="card-text">{{ article.Content }}</p>
						</div>
						<ul class="list-group list-group-flush">
							<li class="list-group-item">{{ article.Description }}</li>
							<li class="list-group-item">{{ article.Releasedate ? article.Releasedate|date('Y-m-d H:i:s') : '' }}</li>
							<li class="list-group-item">{{ article.Statut }}</li>
							{% if app.user %}
								{% if app.user.id == article.User.id %}
									<li class="list-group-item">
										<a class="btn btn-lg btn-primary" href="{{ path('app_private_profil', {'id': article.User.id})}}">{{ article.Author }}</a>
									</li>
								{% else %}
									<li class="list-group-item">
										<a class="btn btn-lg btn-primary" href="{{ path('app_public_profil', {'id': article.User.id})}}">{{ article.Author }}</a>
									</li>
								{% endif %}
							{% endif %}
							<li class="list-group-item">
								<a class="btn btn-lg btn-primary" href="{{ path('app_article_showpublic', {'id': article.id}) }}">
									Show
								</a>
							</li>
						</ul>
					</div>
				</div>
			{% endif %}
		{% endfor %}
	</div>
{% endblock %}